name: "Say Hello Action"
description: "A simple composite action to say Hello"
inputs:
  test:
    description: "Name of the person to greet"
    required: true

runs:
  using: "composite"
  steps:
    - name: Say Hello
      shell: bash
      run: echo "Hello, ${{ inputs.test }}"