name: "Say Hello"
description: "A simple composite action that greets the user"
inputs:
  name:
    description: "Name to greet"
    required: true

runs:
  using: "composite"
  steps:
    - name: Say hello
      run: echo "Hello, ${{ inputs.name }}!"