name: 04 - Using Actions
on:
  push:
  workflow_dispatch:
jobs:
  build:
   runs-on: ubuntu-latest
   steps:
       - name: Git checkout
         uses: actions/checkout@v4
       - name: print the location 
         uses: actions/setup-node@v4
         with:
          node-version: '20.x'
       - name: test 
         run: echo "${{tojson(github)}}"