name: 06 - Contexts
run-name: My custom workflow run name ${{ inputs.debug }}
on:
    push:
    workflow_dispatch:
        inputs:
            debug:
                type: boolean
                description: true and false
                default: false
env:
    MY_VAR: 'hello world'   
jobs:
    echo-data:  
         env:
            MY_OVERWRITTEN_VAR: 'job'
            MY_JOB_VAR: 'job'
         runs-on: ubuntu-latest
         steps: 
            - name: testing
              run: echo "${{toJson(github)}}"
            - name: Display Information
              run: |
                    echo "Event name: ${{github.event_name}}"
                    echo "Ref: ${{github.ref}}"
                    echo "SHA: ${{github.sha}}"
                    echo "Actor: ${{github.actor}}"
                    echo "Workflow: ${{github.workflow}}"
                    echo "Run ID: ${{github.run_id}}"
                    echo "Run number: ${{github.run_number}}"

            - name: Retrieve Variable
              run: echo "${{env.MY_VAR}}"
            
            - name:  Print Env Variables
              env: 
                MY_OVERWRITTEN_VAR: 'steps'
              run: |
                   echo "Workflow env: ${{env.MY_WORKFLOW_VAR}}"
                   echo "Workflow env: ${{env.MY_OVERWRITTEN_VAR }}"

            - name:  Print Env Variables
              run: |
                   echo "Workflow env: ${{env.MY_WORKFLOW_VAR}}"
                   echo "Workflow env: ${{env.MY_OVERWRITTEN_VAR }}"
              