name: 06 - Contexts
run-name: My custom workflow run name - "$RUNNER_OS"
on:
    push:
    workflow_dispatch:
env:
    MY_VAR: hello world        
jobs:
    echo-data:
         runs-on: ubuntu-latest
         steps: 
            - name: testing
              run: echo "${{toJson(github)}}"
            - name: Display Information
              run: |
                    echo "Event name: ${{github.event_name}}"
                    echo "Ref: ${{github.ref}}"
                    echo "SHA: ${{github.sha}}"
                    echo "Actor: ${{github.actor}} 
                    echo "Workflow: ${{github.workflow}}"
                    echo "Run ID: ${{github.run_id}}"
                    echo "Run number: ${{github.run_number}}"

            - name: Retrieve Variable
              run: echo "${{env.MY_VAR}}"

