name: 12 - Working with Outputs
on:
    workflow_dispatch:
            inputs:
                build-status:
                    type: choice
                    description: choice any one of 
                    options:
                        - success
                        - failure
jobs:
    build:
        runs-on: ubuntu-latest
        outputs:
            build-status: "${{steps.build.outputs.status}}"

        steps: 
            - name: Print GITHUB_OUTPUT path
              run: echo "${{steps.build.outputs.status}}"

            - name: Build
              id: build
              run:  echo  "status=${{ inputs.build-status }}" >> "$GITHUB_OUTPUT"
                    

            - name: Print GITHUB_OUTPUT pathece
              run: echo "${{steps.build.outputs.status}}" 

    deploy:
        runs-on: ubuntu-latest
        needs: build
        if: ${{success()}}
        steps: 
            - name: Deploy
              run: echo "Deploying"

            - name: Deploy1
              run: echo "${{needs.build.outputs.build-status}}"
