name: "Use Composite Hello Action"

on:
  workflow_dispatch:

jobs:
  greet:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Call Say Hello Action
        uses: ./.github/actions/say-hello
        with:
          name: "Utsav"