name: "Use Composite Hello Action"

on:
  workflow_dispatch:

jobs:
  greet:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4



      - name: defining the node 
        uses: ./.github/actions/node-version
        with :
           node-version: 20
          